document.addEventListener("DOMContentLoaded", () => {
    handleMessageCreation("Hey, welcome to my portfolio!")
    newMessageTimer("Choose what you would like to do!", 3000)
    handleButtonRender()
    buttonHover()
    handleAboutClick()
    handleProjectsClick()
    handleContactClick()
    handleIconClick()
})